### ISSUE TITLE
Add PneumaticCraft: Repressurized mod

### ISSUE THREAD

**Issue by Mattwell1** [Dayton-10/FreeCraft-III#6]
This mod is an old one, but since we are low on mods we usually use, this might be nice to check out.

[Mod Linkl](https://www.curseforge.com/minecraft/mc-mods/pneumaticcraft-repressurized)

**Comment by Dayton-10** [comment]
I don't think I'm going to add this before release, but I'm open to adding it later if we feel it necessary.
